services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: spriteai
      POSTGRES_PASSWORD: spriteai
      POSTGRES_DB: spriteai
    ports:
      - "5500:5432"
    volumes:
      - spriteai_pg:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: spriteai
      RABBITMQ_DEFAULT_PASS: spriteai

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spriteai.local
      PGADMIN_DEFAULT_PASSWORD: spriteai
    depends_on:
      - postgres

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "50000:50000"
      - "8081:8080"
    volumes:
      - spriteai_jenkins:/var/jenkins_home

volumes:
  spriteai_pg:
  spriteai_jenkins:
